version: '3'
services:
  spring-boot-app:
    build:
      context: ./muconn-backend
      dockerfile: Dockerfile-backend
    ports:
      - "8080:8080"
  react-app:
    build:
      context: ./muconn-frontend
      dockerfile: Dockerfile-frontend
    ports:
      - "3000:3000"
