name: Full Stack CI

on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: windows-latest

    steps:
      - name: Checkout Frontend Code
        uses: actions/checkout@v2
        with:
          path: muconn-frontend

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.6.1

      - name: List Frontend Directory Contents
        run: ls -R muconn-frontend

      - name: Install Frontend Dependencies
        working-directory: muconn-frontend/muconn-frontend
        run: npm install

  backend:
    runs-on: windows-latest

    steps:
      - name: Checkout Backend code
        uses: actions/checkout@v3
        with:
          path: muconn-backend

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin' 
          cache: maven

      - name: List Backend Directory Contents
        run: ls -R muconn-backend
        
      - name: Build and Test Backend
        working-directory: muconn-backend/muconn-backend
        run: mvn clean install

  deploy:
    runs-on: ubuntu-latest

    needs: [frontend, backend]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Frontend Docker Images
        working-directory: muconn-frontend
        run: |
          docker build -t muconn-frontend-image -f Dockerfile-frontend .
          docker push muconn-frontend-image

      - name: Build and Push Backend Docker Images
        working-directory: muconn-backend
        run: |
          docker build -t muconn-backend-image -f Dockerfile-backend .
          docker push muconn-backend-image

      - name: Deploy to Production
        run: |
          docker-compose -f docker-compose.yml down --timeout 30
          docker-compose -f docker-compose.yml pull
          docker-compose -f docker-compose.yml up -d
  
