name: Full Stack CI

on:
  push:
    branches:
      - main

jobs:
  frontend:
    runs-on: windows-latest

    steps:
      - name: Checkout Frontend Code
        uses: actions/checkout@v2
        with:
          path: muconn-frontend

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.6.1

      - name: Install Frontend Dependencies
        working-directory: ./muconn-frontend
        run: npm install

      - name: Run Frontend Tests
        working-directory: ./muconn-frontend
        run: npm test

  backend:
    runs-on: windows-latest

    steps:
      - name: Checkout Backend code
        uses: actions/checkout@v2
        with:
          path: muconn-backend

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '20.6.1'

      - name: Build and Test Backend
        working-directory: ./muconn-backend  
        run: |
          mvn clean install
          mvn test

  sonarqube:
    runs-on: windows-latest 
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Muconn
    

